title: Espaces Marx

remote_theme: mmistakes/minimal-mistakes
url: "https://www.espaces-marx.eu"
baseurl: ""
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
atom_feed:
  hide: true

og_image: /images/illus_marxist_rock.png
  
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:contact@espaces-marx.eu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/espaces-marx/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/espacesmarx"

# Events
  
timezone: Europe/Paris
collections:
  events:
    output: true

# Posts
    
defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

date_format: "%d/%m/%Y"
